baseURL: "https://jshmnrd.ca" 
title: Joshua Maynard
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: about
          url: about/
          weight: 2 
        - name: explore
          url: explore/
          weight: 3
        - name: posts
          url: posts/
          weight: 4
        - name: 🔍
          url:  search/
          weight: 8
        - name: contact
          url: contact/
          weight: 7

params:
    description: "This is my personal website, where I keep pretty much whatever I want myself or others to be able to access freely."
    author: Joshua Maynard
    googleAnalyticsID: "G-9HLZY4NJ0W"
    DateFormat: "02 Jan 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowRssButtonInSectionTermList: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: true
    MainSections: ["about","explore","posts"]
    ShowToc: false
    disableScrollToTop: false
    TocOpen: false
    ShowWordCount: false
    # UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Joshua Maynard
          subtitle: "I am a 25 year old from Toronto, Canada. I'm a geek. I love movies, TV, Dungeons & Dragons and pretty much anything computer-related."
          imageUrl: "jm-transparent.PNG"
          imageWidth: 160
          imageHeight: 160
          buttons:
              - name: start
                url: explore/
            # - name: about
              # url: about/
            # - name: explore
              # url: explore/
            # - name: posts
              # url: posts/
            # - name: contact
              # url: contact/

    socialIcons:
        - name: Twitter
          url: https://twitter.com/bigMoosse/
        - name: Bluesky
          url: https://bsky.app/profile/jshmnrd.ca/
        - name: Mastodon
          url: https://mstdn.ca/@jshmnrd/
        - name: LinkedIn
          url: https://www.linkedin.com/in/maynardjoshua/
        # - name: spacer
        - name: Letterboxd
          url: https://letterboxd.com/jshmnrd/
        - name: Anilist
          url: https://anilist.co/user/joshuamaynard/
        # - name: Bookwyrm
          # url: https://bookwyrm.social/user/jshmnrd/
        # - name: GitHub
          # url: https://github.com/jshmnrd/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Joshua Maynard"
      icon: "favicon.ico"
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search